services:
  api:
    image: brianmatzelle/documenter:latest
    ports:
      - 8080
    container_name: api
    restart: always
    pull_policy: always
    depends_on:
      - ollama
    environment:
      - GIN_MODE=release
      - PORT=8080
    env_file:
      - .env
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434
    volumes:
      - .:/code
      - ./ollama-volume:/root/.ollama
    container_name: ollama
    # pull_policy: always
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  frontend:
    image: brianmatzelle/documenter-frontend:latest
    ports:
      - 3000:3000
    container_name: frontend
    restart: always
    pull_policy: always
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://api:8080

networks:
  ollama-docker:
    external: false